// config.js
module.exports = {
	ontarioColour: {
		greyscale: {
			white: { value: '#FFFFFF' },
		},
		system: {
			link: { value: '#0066CC' },
			linkHover: { value: '#00478F' },
			linkActive: { value: '#002142' },
			linkVisited: { value: '#551A8B' },
			focus: { value: '#009ADB' },
			alert: { value: '#CD0000' },
			alertLight: { value: '#FCEFF0' },
			warning: { value: '#FFD440' },
			warningLight: { value: '#FEF6DC' },
			success: { value: '#118847' },
			successLight: { value: '#E5f0E9' },
			information: { value: '#1080A6' },
			informationLight: { value: '#E2F0F4' },
		},
		accent: {
			main: {
				gold: { value: '#CBA52E' },
				yellow: { value: '#FCAF17' },
				taupe: { value: '#C1B28F' },
				green: { value: '#39B54A' },
				lime: { value: '#8DC63F' },
				teal: { value: '#49A7A2' },
				sky: { value: '#00B2E3' },
				blue: { value: '#3193CC' },
				purple: { value: '#B975B7' },
				orange: { value: '#F15A22' },
				red: { value: '#F0454B' },
				magenta: { value: '#F03093' },
			},
			light: {
				gold: { value: '#F0E7CC' },
				yellow: { value: '#F8E5C3' },
				taupe: { value: '#EBE7DB' },
				green: { value: '#D1EFD4' },
				lime: { value: '#DDEDC7' },
				teal: { value: '#CFEDED' },
				sky: { value: '#C5EEFA' },
				blue: { value: '#DBE9F5' },
				purple: { value: '#F1E3F2' },
				orange: { value: '#FEE1D9' },
				red: { value: '#FFE0E2' },
				magenta: { value: '#FEDFF0' },
			},
			dark: {
				gold: { value: '#86743D' },
				yellow: { value: '#8A600D' },
				taupe: { value: '#7B725C' },
				green: { value: '#2B8737' },
				lime: { value: '#5F8129' },
				teal: { value: '#367A76' },
				sky: { value: '#1080A6' },
				blue: { value: '#0369ac' },
				purple: { value: '#92278F' },
				orange: { value: '#C64A1C' },
				red: { value: '#D81A21' },
				magenta: { value: '#C00264' },
			},
			calloutBackgrounds: {
				red: { value: '#FCEFF0' },
				green: { value: '#E5F0E9' },
				yellow: { value: '#FEF6DC' },
			},
			iconColours: {
				blue: { value: '#0066CC' },
				grey: { value: '#666666' },
				black: { value: '#1A1A1A' },
				white: { value: '#FFFFFF' },
			},
		},
	},
};
