FROM mcr.microsoft.com/playwright:v1.54.0-noble

# Set the working directory
WORKDIR /app

# copy monorepo
COPY . .

# Make start-server.sh executable
RUN chmod +x scripts/start-server.sh

# Set up pnpm 
RUN npm install -g pnpm

# Install deps & build libs
RUN rm -rf node_modules && \
    pnpm install --frozen-lockfile
