packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  core-js-pure: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  nx: false
  puppeteer: false
  sharp: false
  unrs-resolver: false
patchedDependencies:
  '@semantic-release/github@12.0.9': patches/@semantic-release__github@12.0.9.patch
  conventional-changelog-angular@8.0.0: patches/conventional-changelog-angular@8.0.0.patch
  ngx-translate-routes@2.3.3: patches/ngx-translate-routes@2.3.3.patch
