/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * Friendly label to demonstrate prop passing in generated samples.
          * @default 'value'
         */
        "prop": string;
    }
    interface SampleButton {
        /**
          * Button style variant used in generated samples.
          * @default 'primary'
         */
        "type": ButtonVariant;
    }
    interface SampleCard {
        /**
          * Headline for the card surface.
          * @default 'Heading'
         */
        "heading": string;
        /**
          * Status badge label rendered in the header.
          * @default 'Draft'
         */
        "status": string;
        /**
          * Supporting summary text displayed beneath the heading.
          * @default 'Summary text goes here.'
         */
        "summary": string;
    }
    interface SampleCardAction {
        /**
          * Optional link target for the action.
         */
        "href"?: string;
        /**
          * Text label displayed for the action.
          * @default 'Action'
         */
        "label": string;
        /**
          * Visual variant for the action control.
          * @default 'primary'
         */
        "variant": ActionVariant;
    }
    interface SampleInput {
        /**
          * Label displayed above the input field.
          * @default 'Label'
         */
        "label": string;
        /**
          * Placeholder text shown inside the input.
          * @default 'Type something...'
         */
        "placeholder": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSampleButtonElement extends Components.SampleButton, HTMLStencilElement {
    }
    var HTMLSampleButtonElement: {
        prototype: HTMLSampleButtonElement;
        new (): HTMLSampleButtonElement;
    };
    interface HTMLSampleCardElement extends Components.SampleCard, HTMLStencilElement {
    }
    var HTMLSampleCardElement: {
        prototype: HTMLSampleCardElement;
        new (): HTMLSampleCardElement;
    };
    interface HTMLSampleCardActionElement extends Components.SampleCardAction, HTMLStencilElement {
    }
    var HTMLSampleCardActionElement: {
        prototype: HTMLSampleCardActionElement;
        new (): HTMLSampleCardActionElement;
    };
    interface HTMLSampleInputElement extends Components.SampleInput, HTMLStencilElement {
    }
    var HTMLSampleInputElement: {
        prototype: HTMLSampleInputElement;
        new (): HTMLSampleInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sample-button": HTMLSampleButtonElement;
        "sample-card": HTMLSampleCardElement;
        "sample-card-action": HTMLSampleCardActionElement;
        "sample-input": HTMLSampleInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * Friendly label to demonstrate prop passing in generated samples.
          * @default 'value'
         */
        "prop"?: string;
    }
    interface SampleButton {
        /**
          * Button style variant used in generated samples.
          * @default 'primary'
         */
        "type"?: ButtonVariant;
    }
    interface SampleCard {
        /**
          * Headline for the card surface.
          * @default 'Heading'
         */
        "heading"?: string;
        /**
          * Status badge label rendered in the header.
          * @default 'Draft'
         */
        "status"?: string;
        /**
          * Supporting summary text displayed beneath the heading.
          * @default 'Summary text goes here.'
         */
        "summary"?: string;
    }
    interface SampleCardAction {
        /**
          * Optional link target for the action.
         */
        "href"?: string;
        /**
          * Text label displayed for the action.
          * @default 'Action'
         */
        "label"?: string;
        /**
          * Visual variant for the action control.
          * @default 'primary'
         */
        "variant"?: ActionVariant;
    }
    interface SampleInput {
        /**
          * Label displayed above the input field.
          * @default 'Label'
         */
        "label"?: string;
        /**
          * Placeholder text shown inside the input.
          * @default 'Type something...'
         */
        "placeholder"?: string;
    }

    interface MyComponentAttributes {
        "prop": string;
    }
    interface SampleButtonAttributes {
        "type": ButtonVariant;
    }
    interface SampleCardAttributes {
        "heading": string;
        "summary": string;
        "status": string;
    }
    interface SampleCardActionAttributes {
        "label": string;
        "variant": ActionVariant;
        "href": string;
    }
    interface SampleInputAttributes {
        "label": string;
        "placeholder": string;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "sample-button": Omit<SampleButton, keyof SampleButtonAttributes> & { [K in keyof SampleButton & keyof SampleButtonAttributes]?: SampleButton[K] } & { [K in keyof SampleButton & keyof SampleButtonAttributes as `attr:${K}`]?: SampleButtonAttributes[K] } & { [K in keyof SampleButton & keyof SampleButtonAttributes as `prop:${K}`]?: SampleButton[K] };
        "sample-card": Omit<SampleCard, keyof SampleCardAttributes> & { [K in keyof SampleCard & keyof SampleCardAttributes]?: SampleCard[K] } & { [K in keyof SampleCard & keyof SampleCardAttributes as `attr:${K}`]?: SampleCardAttributes[K] } & { [K in keyof SampleCard & keyof SampleCardAttributes as `prop:${K}`]?: SampleCard[K] };
        "sample-card-action": Omit<SampleCardAction, keyof SampleCardActionAttributes> & { [K in keyof SampleCardAction & keyof SampleCardActionAttributes]?: SampleCardAction[K] } & { [K in keyof SampleCardAction & keyof SampleCardActionAttributes as `attr:${K}`]?: SampleCardActionAttributes[K] } & { [K in keyof SampleCardAction & keyof SampleCardActionAttributes as `prop:${K}`]?: SampleCardAction[K] };
        "sample-input": Omit<SampleInput, keyof SampleInputAttributes> & { [K in keyof SampleInput & keyof SampleInputAttributes]?: SampleInput[K] } & { [K in keyof SampleInput & keyof SampleInputAttributes as `attr:${K}`]?: SampleInputAttributes[K] } & { [K in keyof SampleInput & keyof SampleInputAttributes as `prop:${K}`]?: SampleInput[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sample-button": LocalJSX.IntrinsicElements["sample-button"] & JSXBase.HTMLAttributes<HTMLSampleButtonElement>;
            "sample-card": LocalJSX.IntrinsicElements["sample-card"] & JSXBase.HTMLAttributes<HTMLSampleCardElement>;
            "sample-card-action": LocalJSX.IntrinsicElements["sample-card-action"] & JSXBase.HTMLAttributes<HTMLSampleCardActionElement>;
            "sample-input": LocalJSX.IntrinsicElements["sample-input"] & JSXBase.HTMLAttributes<HTMLSampleInputElement>;
        }
    }
}
