import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
	{
		path: '/developer-docs/__docusaurus/debug',
		component: ComponentCreator('/developer-docs/__docusaurus/debug', 'b77'),
		exact: true,
	},
	{
		path: '/developer-docs/__docusaurus/debug/config',
		component: ComponentCreator('/developer-docs/__docusaurus/debug/config', '3d1'),
		exact: true,
	},
	{
		path: '/developer-docs/__docusaurus/debug/content',
		component: ComponentCreator('/developer-docs/__docusaurus/debug/content', '8bc'),
		exact: true,
	},
	{
		path: '/developer-docs/__docusaurus/debug/globalData',
		component: ComponentCreator('/developer-docs/__docusaurus/debug/globalData', 'cb8'),
		exact: true,
	},
	{
		path: '/developer-docs/__docusaurus/debug/metadata',
		component: ComponentCreator('/developer-docs/__docusaurus/debug/metadata', 'ef1'),
		exact: true,
	},
	{
		path: '/developer-docs/__docusaurus/debug/registry',
		component: ComponentCreator('/developer-docs/__docusaurus/debug/registry', '720'),
		exact: true,
	},
	{
		path: '/developer-docs/__docusaurus/debug/routes',
		component: ComponentCreator('/developer-docs/__docusaurus/debug/routes', '601'),
		exact: true,
	},
	{
		path: '/developer-docs/',
		component: ComponentCreator('/developer-docs/', '230'),
		routes: [
			{
				path: '/developer-docs/',
				component: ComponentCreator('/developer-docs/', '578'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/category/web-component-api-docs',
				component: ComponentCreator('/developer-docs/category/web-component-api-docs', '7c2'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-accordion/',
				component: ComponentCreator('/developer-docs/components/ontario-accordion/', '2d7'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-aside/',
				component: ComponentCreator('/developer-docs/components/ontario-aside/', '9c5'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-back-to-top/',
				component: ComponentCreator('/developer-docs/components/ontario-back-to-top/', '5fa'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-badge/',
				component: ComponentCreator('/developer-docs/components/ontario-badge/', 'f71'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-blockquote/',
				component: ComponentCreator('/developer-docs/components/ontario-blockquote/', '9c8'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-button/',
				component: ComponentCreator('/developer-docs/components/ontario-button/', '741'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-callout/',
				component: ComponentCreator('/developer-docs/components/ontario-callout/', '96c'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-card-collection/',
				component: ComponentCreator('/developer-docs/components/ontario-card-collection/', 'f4c'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-card/',
				component: ComponentCreator('/developer-docs/components/ontario-card/', '09e'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-checkbox/',
				component: ComponentCreator('/developer-docs/components/ontario-checkbox/', 'db3'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-critical-alert/',
				component: ComponentCreator('/developer-docs/components/ontario-critical-alert/', '21d'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-date-input/',
				component: ComponentCreator('/developer-docs/components/ontario-date-input/', 'c5d'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-dropdown-list/',
				component: ComponentCreator('/developer-docs/components/ontario-dropdown-list/', 'c25'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-fieldset/',
				component: ComponentCreator('/developer-docs/components/ontario-fieldset/', '689'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-footer/',
				component: ComponentCreator('/developer-docs/components/ontario-footer/', '3d4'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-header/',
				component: ComponentCreator('/developer-docs/components/ontario-header/', 'd93'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-hint-expander/',
				component: ComponentCreator('/developer-docs/components/ontario-hint-expander/', 'adc'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-hint-text/',
				component: ComponentCreator('/developer-docs/components/ontario-hint-text/', '571'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-icon/',
				component: ComponentCreator('/developer-docs/components/ontario-icon/', '6be'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-input/',
				component: ComponentCreator('/developer-docs/components/ontario-input/', '742'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-language-toggle/',
				component: ComponentCreator('/developer-docs/components/ontario-language-toggle/', '953'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-loading-indicator/',
				component: ComponentCreator('/developer-docs/components/ontario-loading-indicator/', '884'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-page-alert/',
				component: ComponentCreator('/developer-docs/components/ontario-page-alert/', '7c4'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-radio-buttons/',
				component: ComponentCreator('/developer-docs/components/ontario-radio-buttons/', 'aa6'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-search-box/',
				component: ComponentCreator('/developer-docs/components/ontario-search-box/', '67b'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-step-indicator/',
				component: ComponentCreator('/developer-docs/components/ontario-step-indicator/', 'd4b'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-table/',
				component: ComponentCreator('/developer-docs/components/ontario-table/', '8d2'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-task-list/',
				component: ComponentCreator('/developer-docs/components/ontario-task-list/', 'd67'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-task/',
				component: ComponentCreator('/developer-docs/components/ontario-task/', 'ccc'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/components/ontario-textarea/',
				component: ComponentCreator('/developer-docs/components/ontario-textarea/', 'e80'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/readme-angular',
				component: ComponentCreator('/developer-docs/readme-angular', 'af4'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/readme-complete-styles',
				component: ComponentCreator('/developer-docs/readme-complete-styles', '1af'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/readme-design-tokens',
				component: ComponentCreator('/developer-docs/readme-design-tokens', '7aa'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/readme-global-styles',
				component: ComponentCreator('/developer-docs/readme-global-styles', '6d9'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
			{
				path: '/developer-docs/readme-react',
				component: ComponentCreator('/developer-docs/readme-react', '8d4'),
				exact: true,
				sidebar: 'tutorialSidebar',
			},
		],
	},
	{
		path: '*',
		component: ComponentCreator('*'),
	},
];
