// content automatically generated by `generate-icons.js` begins
import { Component, Prop, h, Watch, State } from '@stencil/core';
import { Icon } from './icon.interface';
import { IconSize} from './ontario-icon.enum';
import { ConsoleType, MessageStyle } from '../../utils/console-message/console-message.enum';
import { printConsoleMessage } from '../../utils/console-message/console-message';

@Component({
    tag: 'ontario-icon-dropdown-arrow',
    styleUrl: 'ontario-icon.scss',
    shadow: true,
})
export class OntarioIconDropdownArrow implements Icon {
    /**
     * The icon width will autogenerate the height since the icons are in square format, thus preserving
     * the aspect ratio.
     */
    @Prop() iconWidth: number = IconSize.DEFAULT;

    /**
	 * Mutable variable, for internal use only.
	 * Set the icon's width depending on validation result.
	 */
	@State() iconWidthState: number = IconSize.DEFAULT;

    /**
     * Watch for changes in the `iconWidth` variable for validation purpose.
     * If the user input is not a number or is a negative number then `iconWidth` will be set to its default (24).
     */
    @Watch('iconWidth')
    validateWidth() {
		if (isNaN(this.iconWidth) || (!isNaN(this.iconWidth) && this.iconWidth <= 0)) {
			printConsoleMessage([
        {
            message: '%c icon-width ',
            style: MessageStyle.CODE,
        },
        {
            message: '%con',
            style: MessageStyle.REGULAR,
        },
        {
            message: `%c <ontario-icon-dropdown-arrow> `,
            style: MessageStyle.CODE,
        },
        {
            message: `%cwas set to a non-numeric value; only positive number is allowed. The default size of`,
            style: MessageStyle.REGULAR,
        },
        {
            message: '%c 24px ',
            style: MessageStyle.CODE,
        },
        {
            message: '%cwas assumed.',
            style: MessageStyle.REGULAR,
        },
    ], ConsoleType.WARNING);
			this.iconWidthState = IconSize.DEFAULT;
		} else {
			this.iconWidthState = this.iconWidth;
		}
    }
    
	/**
	 * Stencil component lifecycle method that is called once after the component is first connected to the DOM.
	 */
    componentWillLoad() {
        this.validateWidth();
    }

    /**
	 * Returns the HTML code to be rendered into a custom element.
	 */
    render() {
        return (
            <div class='ontario-icon' style={{ 'width': `${this.iconWidthState}px` }}>
                <svg class="svg-icon" role="img" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" id="dropdown-arrow"><path d="M7.965 10a.4.4 0 0 0-.37.247.4.4 0 0 0 .087.436l4.035 4.035a.4.4 0 0 0 .566 0l4.035-4.035a.4.4 0 0 0 .087-.436.4.4 0 0 0-.37-.247h-8.07z"/></svg>
            </div>
        );
    }
};
// content automatically generated by `generate-icons.js` ends
